spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

sonar:
  projectKey: jinlee1703-csalgo
  organization: jinlee1703
  host:
    url: https://sonarcloud.io
  sources: src/main
  tests: src/test
  java:
    binaries: build
  coverage:
    jacoco:
      xmlReportPaths: build/reports/jacoco/test/jacocoTestReport.xml
